baseURL = "https://example.com"  # add your website here

[params]
  css_js_version = "12.0"  # change to bypass browser cache

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false
